pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '2.1.x'
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    zipAfterPublish: false
    modifyOutputPath: true
    arguments: '--configuration $(buildConfiguration) -o testpath'
  displayName: 'dotnet publish $(buildConfiguration)'
